=== mosip/mosip-compliance-toolkit/resources/schemas/testcase_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema#",
	"$id": "http://mosip-compliance-toolkit.com/schemas/testcase_schema.json",
	"type": "object",
	"title": "Test Case Schema",
	"description": "Test Case Schema",
	"additionalProperties": false,
	"properties": {
		"testCaseType": {
			"type": "string",
			"enum": [
				"SBI",
				"ABIS",
				"SDK"
			]
		},
		"testName": {
			"type": "string"
		},
		"testId": {
			"type": "string"
		},
		"specVersion": {
			"type": "string",
			"enum": [
				"0.9.5",
				"0.9.0",
				"1.0.0"
			]
		},
		"testDescription": {
			"type": "string"
		},
		"isNegativeTestcase": {
			"type": "boolean"
		},
		"inactive": {
			"type": "boolean"
		},
		"methodName": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": [
					"device",
					"info",
					"capture",
					"rcapture",
					"stream",
					"insert",
					"identify",
					"delete",
					"init",
					"check-quality",
					"match",
					"extract-template",
					"convert-format",
					"segment"
				]
			}
		},
		"requestSchema": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"responseSchema": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"validatorDefs": {
			"type": "array",
			"items": [
				{
					"type": "array",
					"items": [
						{
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"description": {
									"type": "string"
								}
							},
							"required": [
								"name",
								"description"
							]
						}
					]
				}
			]
		},
		"otherAttributes": {
			"type": "object",
			"properties": {
				"purpose": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"Auth",
							"Registration"
						]
					}
				},
				"biometricTypes": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"Finger",
							"Iris",
							"Face"
						]
					}
				},
				"deviceSubTypes": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"Slap",
							"Single",
							"Touchless",
							"Single",
							"Double",
							"Full face"
						]
					}
				},
				"segments": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"LeftIndex",
							"LeftMiddle",
							"LeftRing",
							"LeftLittle",
							"LeftThumb",
							"RightIndex",
							"RightMiddle",
							"RightRing",
							"RightLittle",
							"RightThumb",
							"UNKNOWN",
							"Left",
							"Right"
						]
					}
				},
				"exceptions": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"LeftIndex",
							"LeftMiddle",
							"LeftRing",
							"LeftLittle",
							"LeftThumb",
							"RightIndex",
							"RightMiddle",
							"RightRing",
							"RightLittle",
							"RightThumb",
							"UNKNOWN",
							"Left",
							"Right"
						]
					}
				},
				"requestedScore": {
					"type": [
						"string",
						"null"
					]
				},
				"bioCount": {
					"type": [
						"string",
						"null"
					]
				},
				"deviceSubId": {
					"type": [
						"string",
						"null"
					]
				},
				"timeout": {
					"type": [
						"string",
						"null"
					]
				},
				"resumeBtn": {
					"type": "boolean"
				},
				"resumeAgainBtn": {
					"type": "boolean"
				},
				"keyRotationTestCase": {
					"type": "boolean"
				},
				"transactionId":{
					"type": "string"
				},
				"invalidAttributeName":{
					"type": "string"
				},
				"modalities": {
					"type": "array",
					"items": [
						{
							"type": "string"
						}
					]
				},
				"sdkPurpose": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"Check Quality",
							"Matcher",
							"Extract Template",
							"Convert Format",
							"Segment"
						]
					}
				},
				"convertSourceFormat": {
					"type": "string",
					"enum": [
						"ISO19794_4_2011",
						"ISO19794_5_2011",
						"ISO19794_6_2011"
					]
				},
				"convertTargetFormat": {
					"type": "string",
					"enum": [
						"IMAGE/JPEG",
						"IMAGE/PNG",
						"ISO19794_4_2011/JPEG",
						"ISO19794_5_2011/JPEG",
						"ISO19794_4_2011/PNG",
						"ISO19794_5_2011/PNG",
						"ISO19794_6_2011/PNG"
					]
				}
			}
		}
	},
	"required": [
		"testCaseType",
		"testId",
		"testName",
		"testDescription",
		"isNegativeTestcase",
		"methodName",
		"requestSchema",
		"responseSchema",
		"validatorDefs"
	],
	"allOf": [
		{
			"if": {
				"properties": {
					"testCaseType": {
						"const": "SBI"
					}
				}
			},
			"then": {
				"properties": {
					"otherAttributes": {
						"required": [
							"purpose",
							"biometricTypes",
							"deviceSubTypes",
							"segments",
							"exceptions",
							"requestedScore",
							"bioCount",
							"deviceSubId"
						]
					},
					"specVersion": {
						"enum": [
							"0.9.5",
							"1.0.0"
						]
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"testCaseType": {
						"const": "SDK"
					}
				}
			},
			"then": {
				"if": {
					"properties": {
						"methodName": {
							"const": "convert-format"
						}
					}
				},
				"then": {
					"properties": {
						"otherAttributes": {
							"required": [
								"modalities",
								"convertSourceFormat",
								"convertTargetFormat"
							]
						},
						"specVersion": {
							"enum": [
								"0.9.0"
							]
						}
					}
				},
				"else": {
					"properties": {
						"otherAttributes": {
							"required": [
								"modalities"
							]
						},
						"specVersion": {
							"enum": [
								"0.9.0"
							]
						}
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"testCaseType": {
						"const": "ABIS"
					}
				}
			},
			"then": {
				"properties": {
					"otherAttributes": {
						"required": [
							"modalities"
						]
					},
					"specVersion": {
						"enum": [
							"0.9.0"
						]
					}
				}
			}
		}
	]
}

=== mosip/mosip-compliance-toolkit/resources/compliance_test_definitions_abis.json
[
	{
		"testCaseType": "ABIS",
		"testName": "Insert one person\"s biomterics in ABIS",
		"testId": "ABIS3000",
		"specVersion": "0.9.0",
		"testDescription": "Insert one person\"s biomterics in ABIS",
		"isNegativeTestcase": false,
		"methodName": [
			"insert"
		],
		"requestSchema": [
			"InsertRequestSchema"
		],
		"responseSchema": [
			"InsertResponseSchema"
		],
		"validatorDefs": [
			[
				{
					"name": "SchemaValidator",
					"description": "Validates if response has all mandatory attributes and they have allowed values"
				}
			]
		],
		"otherAttributes": {
			"abisPurpose": [
				"Insert"
			],
			"cbeffFilesCount": "1"
		}
	},
	{
		"testCaseType": "ABIS",
		"testName": "Insert two person\"s biomterics in ABIS",
		"testId": "ABIS3001",
		"specVersion": "0.9.0",
		"testDescription": "Insert two person\"s biomterics in ABIS",
		"isNegativeTestcase": false,
		"methodName": [
			"insert"
		],
		"requestSchema": [
			"InsertRequestSchema"
		],
		"responseSchema": [
			"InsertResponseSchema"
		],
		"validatorDefs": [
			[
				{
					"name": "SchemaValidator",
					"description": "Validates if response has all mandatory attributes and they have allowed values"
				}
			]
		],
		"otherAttributes": {
			"cbeffFilesCount": "2"
		}
	},
	{
		"testCaseType": "ABIS",
		"testName": "Identify - successful in finding a duplicate match",
		"testId": "ABIS3017",
		"specVersion": "0.9.0",
		"testDescription": "Identify - successful in finding a duplicate match",
		"isNegativeTestcase": false,
		"methodName": [
			"identify"
		],
		"requestSchema": [
			"IdentifyRequestSchema"
		],
		"responseSchema": [
			"IdentifyResponseSchema"
		],
		"validatorDefs": [
			[
				{
					"name": "SchemaValidator",
					"description": "Validates if response has all mandatory attributes and they have allowed values"
				}
			]
		],
		"otherAttributes": {
			"cbeffFilesCount": "1",
			"referenceTestId": "ABIS3000"
		}
	}
]
